import Head from 'next/head'

import Header from '@/components/header'
import Footer from '@/components/footer'
import Content from '@/components/content'

export default function Home() {
  const footerData = {
    additionalResources: "Links to the university's social media, blog, and other relevant pages",
    contactInformation: "Phone number, and office hours",
  };
  const headerData = {
    studentName: "Hari"
  }
  const contentData = {
    universityName:"RMIT",
    courseName:"Bachelor of Engineering"
  }
  return (
    <>
      <Head>
        <title>Propose - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header headerResponse={headerData}></Header>
      <main>
        <Content contentResponse={contentData}></Content>
       </main>
      <Footer footerResponse={footerData}></Footer>
    </>
  )
}
